### ISSUE TITLE
webcomponents-hi-sd-ce.js not working on Firefox (-lite.js is working instead)

### ISSUE THREAD

**Issue by LasaleFamine** [webcomponents/webcomponentsjs#846]
I'm using the `webcomponents-loader.js` to load the polyfills, but I'm seeing my Polymer 3 application got broken when opened in Firefox (and also Edge, but there's another problem).

The **loader** tries to load the `webcomponents-hi-sd-ce.js`, loads it, but I'm getting the error:

```
TypeError: window.customElements is undefined
```

After this I have tried to force the loading of the `webcomponents-lite.js` polyfill and now everything is working normally.
I must assume that the `webcomponents-hi-sd-ce.js` is broken? Or maybe the **loader** loads the wrong polyfill?

**Comment by equinusocio** [comment]
Same here on Firefox Developer Edition.

**Comment by LasaleFamine** [comment]
Just for completition: even the `webcomponents-sd-ce.js` seems broken/not working.

**Comment by adnion** [comment]
For me both `webcomponents-sd-ce.js` and `webcomponents-lite.js` don't work with Firefox (56.0.1) and Edge (using Html imports only).

**Comment by hiro2016** [comment]
@version 0.7.23 of `webcomponents.min.js` works on firefox.  
@version 0.7.23 `lib/webcomponents-lite.js` does not work.   
https://github.com/dart-lang/web-components/blob/master/lib/webcomponents.min.js
  
On Firefox 56.0 64 bit ubuntu    
Both webcomponents-lite.js and webcomponents-sd-ce.js or webcomponents-loader.js do not work on firefox.    
  
I'm using dart, so my issue might have nothing to do with this lib though:  
```
TypeError: $document.registerElement is not a function[Learn More]  html_dart2js.dart:45749:2
	_registerCustomElement html_dart2js.dart:45749:2
	dart<.main< html_dart2js.dart:19727:4
	eval$1 isolate_helper.dart:474:15
	startRootIsolate isolate_helper.dart:129:4
	<anonymous> http://localhost:3000/keyboard_elements.js:9303:9
	<anonymous> http://localhost:3000/keyboard_elements.js:9302:8
	<anonymous> http://localhost:3000/keyboard_elements.js:9284:7
	<anonymous> http://localhost:3000/keyboard_elements.js:9278:4
	<anonymous> http://localhost:3000/keyboard_elements.js:21:2
```

Wanted to switch to the latest script since the old script has some compatibility issue with rails jquery and bang something goes wrong.   
Everyone switch to chrome please!!

**Comment by ernsheong** [comment]
I think the issue is that there is nothing wrong with `webcomponents-hi-sd-ce.js` itself, it just needs to be loaded and run first before anything else happens. 

This means that if you use `webcomponents-loader.js` you need to wait on the `WebComponentsReady` event before running Polymer Application code (example uses HTMLWebpackPlugin):

```js
document.addEventListener("WebComponentsReady", function componentsReady() {
    document.removeEventListener("WebComponentsReady", componentsReady, false);

    const script = document.createElement("script");
    script.src = "<%= htmlWebpackPlugin.files.js[0] %>";
    var refScript = document.getElementsByTagName("script")[0];
    refScript.parentNode.insertBefore(script, refScript);
}, false);
```

And to mitigate the time delay for loading the application code you can use:

```html
<link rel="preload" href="<%= htmlWebpackPlugin.files.js[0] %>" as="script">
```

**Comment by LasaleFamine** [comment]
This is a great hint and it solves the problem! This is actually how I loaded my bundle while using the `webcomponents-lite.js`. I don't even remember why I was thinking I didn't need it anymore.

The @ernsheong's implementation solves also the problems with Edge.

So I think we can close this one, since it is not a polyfill's bug. Thank you so much @ernsheong.

**Comment by chisholmd** [comment]
@ernsheong could you please expand on your answer?  For example wtf is this?  
<%= htmlWebpackPlugin.files.js[0] %>

Maybe a plain example, and then the preload version.  I totally get what your talking about having to wait for webcomponents-hi-sd-ce.js to load but I have no idea what call to make to boot my app once it has loaded.
thx

**Comment by LasaleFamine** [comment]
@chisholmd the `<%= htmlWebpackPlugin.files.js[0] %>` is the reference to the `html-webpack-plugin`, but basically is nothing more than your components' bundle, your component's js.

**Comment by chisholmd** [comment]
Thanks...so if I turned bundling on in the polymer cli build I would see what file to put in there?  What if one was not using bundling?

**Comment by chisholmd** [comment]
" nothing more than your components' bundle, your component's js."  

Sry but I just don't understand this statement.  When I build with "bundle" I get an index.html and a thin bower_components folder with webcomponents and not much else.  

I have an "app" element, is that what I should be calling?  So instead of 
    script.src = "<%= htmlWebpackPlugin.files.js[0] %>";
I should use
    script.src = "my-app.html";

What is "Your components bundle"
What is "your component's js."

Thank you for your help, this app is done and works great on Chrome and I am trying to deliver.

**Comment by LasaleFamine** [comment]
Sorry, I've taken too many things for granted. 
We were talking about Polymer (3.x specifically) application but built with Webpack. So we were talking about JS files and not HTML.

You have to import your HTML using an HTML import. You must change the code shown by @ernsheong to make this work. I'm currently from phone, it's a bit tedious to explain from here. I will come up with an example, if someone will not anticipate me!

**Comment by chisholmd** [comment]
Sry I did't even notice this thread started with polymer 3.  I really appriciate your help.

**Comment by ernsheong** [comment]
I am on Polymer 2, using the [polymer-webpack-loader](https://github.com/webpack-contrib/polymer-webpack-loader). Replace that snippet with whatever name your bundle is, using whatever tool you like.

**Comment by chisholmd** [comment]
I will give this a shot.  Where I am at now is that I can trap the debugger in the constructor block of my main app, but it never gets to the ready() block.   If it is just going to die it would be nice if it throw some sort of error :(.

**Comment by hiro2016** [comment]
Thanks @ernsheong  
Sorry about not responding.     
  
It did not help my case. But your hack helped me to rule out the possibility of timing issue.  


### Rails  how to  use ernsheong's hack  
Tested on: firefox quontum 57.0.1 for ubuntu with ruby on rails.   
Note: The speed was not ideal as compared to using the older version of polyfill; I could use the old script like other javascript libraries and let rails asset pipeline and turbolinks do the job.
***

In one of view tamplate that uses a custom html element.  
```
document.addEventListener("WebComponentsReady", function componentsReady() {
    document.removeEventListener("WebComponentsReady", componentsReady, false);
    const script = document.createElement("script");
    script.src = "<%= javascript_include_tag('custom_elements').match(/\".*\"/).to_s.gsub(/\"/,'') %>";
    var refScript = document.getElementsByTagName("script")[0];
    refScript.parentNode.insertBefore(script, refScript);
}, false);
```  
javascript manifest file `app/assets/javascripts/application.js`
```
//= require rails-ujs
//= require turbolinks
//= require jquery
//= require jquery_ujs
//= require bootstrap 
//= require webcomponents.min
// require webcomponents-lite
```  
javascript manifest file `app/assets/javascripts/custom_elements.js`  
```
// A custom html element I wrote using dart; compiled to javascript
//= require keyboard_elements 
```
Append the line below to `config/initializer/assets.rb`
```
Rails.application.config.assets.precompile += %w( custom_elements.js )
```
  
Needles to say, `custom_elements.js` name is merely one I picked for my script. Your script name has to replace it.   
***  
#### My dart script failed even with the hack, but the hack might work for others.
Asap I removed my ancient webcomponents.min and turn on the newish webcomponents-lite like below
```
//= require webcomponents-lite
// require webcomponents.min
```
```
GET
http://localhost:3000/assets/keyboard_elements.self-07ebf415b04b9f2c3a7a1b073dbbd1911403e34aa102d0319b9f360e17e420ae.js
[HTTP/1.1 200 OK 0ms]
TypeError: $document.registerElement is not a function
```  
Hmmm, I will give up.   
Since timing issue is out, I guess it's name binding;dart side library is bound to a specific version of polyfill maybe.
***

**Comment by trusktr** [comment]
@hiro2016 The new webcomponents uses Custom Elements v1, which means you need to use `customElements.define` instead of `document.registerElement`.

---

I also can't get this to work in Firefox and Edge. In both Firefox and Edge, attributeChangedCallback of my components aren't being called.

 I've tried `-loader.js` and `-sd-ce.js` both as the very first `<script>`s in the page, with both listening for `WebComponentsReady` and not listening. I've also tried calling `customElements.define` **_before and after_** the `WebComponentsReady` has fired. No matter which permutations I can think of trying, `attributeChangedCallback` fires **for only some attributes**, and which ones it fires for is consistent between Firefox and Edge.

I've tried just about everything I've read in issues like this one and the README. 

My site is at http://trusktr.io

It works in Chrome, and Safari, where the sidebar background should be full height of the window.

You can select the `#menuNode` and try modifying it in console in Chrome,

```js
var el = document.querySelector('#menuNode')
el.setAttribute('sizeMode', 'literal literal literal')`
```

and you'll see that the result will become like what you see in Firefox. This is because the value before changing this attribute is `"literal proportional literal"`, but this value never gets set in Firefox, and setting it in Firefox does nothing.

F.e. in Firefox try

```js
var el = document.querySelector('#menuNode')
el.setAttribute('sizeMode', 'literal literal literal') // change it
el.setAttribute('sizeMode', 'literal proportional literal') // set it back
```

which should make the element size mode the same as in Chrome and therfore the sidebar background should be full-height, but nothing happens.

It can be verified that attributeChangeCallback is not firing by running

```js
el.sizeMode
```

after attempting those attribute changes, but you'll see that the values inside that object (which get internally updated by `attributeChangedCallback`) never change and are always the same.

This seems to indicate that I'm having issues with `attributeChangedCallback` like others have described, however I just can't figure out how to get it working yet.

I'll keep investigating...

**Comment by trusktr** [comment]
The only thing I haven't tried is using `customElements.define` before the webcomponents scripts, but that doesn't seem to make sense, as `customElements.define` will not exist. I'm not sure what else to try.

**Comment by trusktr** [comment]
(Good thing is, I can skip using attributes, and use the JavaScript APIs on the instances to set properties, and that's a workaround for me at the moment)

**Comment by trusktr** [comment]
I updated my site so that attributeChangedCallback outputs ________, so running `el.setAttribute('sizeMode', 'literal literal literal')` should trigger this message (it does in Chrome and Safari). But there's no output in FF or Edge, so it's clearly `attributeChangedCallback` just not being fired for certain attributes. Hmmmmm...

**Comment by trusktr** [comment]
I applied the workaround using JS API on the instances instead of attributes, so you'll see that my site's sidebar works in Firefox and Edge now. However, if you do try setting the attributes in the console, it still won't work in case you're curious to try it.
