### ISSUE TITLE
Version  2.1.1 master doesn't compile

### ISSUE THREAD

**Issue by steelraiden** [webcomponents/webcomponentsjs#995]
- I cloned the git repository
- I have node.js (last version)
- ran npm install -g gulp
- I have java installed (last version)
- ran npm install
- ran npm run build

Error:
> gulp
[00:27:27] Using gulpfile ~\Desktop\webcomponentsjs-master\gulpfile.js
[00:27:27] Starting 'closure'...
[00:27:27] Starting 'clean'...
[00:27:27] Finished 'clean' after 21 ms
[00:27:27] Starting 'closurify-ce'...

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Compilation error: Unhandled flag: outputWrapperFile
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @webcomponents/webcomponentsjs@2.1.1 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @webcomponents/webcomponentsjs@2.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by TimvdLippe** [comment]
I don't seem to have a problem when building. Are you sure you have Java installed? If so, which version of Java are you running?

**Comment by TimvdLippe** [comment]
Closing per above comment. Feel free to reopen if you are still encountering issues.

**Comment by AaronNGray** [comment]
Does not build on Windows with Java jdk-10.0.2_windows-x64_bin.exe
Getting same error as @steelraiden.

**java** is on the command line but **NOT** **javac**

**Comment by TimvdLippe** [comment]
This might actually be related to https://github.com/Polymer/tools/issues/405 Could you try with Java 8 and see if that fixes the issue?

**Comment by AaronNGray** [comment]
okay will do

**Comment by AaronNGray** [comment]
@TimvdLippe what platform are you using please ?

**Comment by TimvdLippe** [comment]
I am running Java 8 and Node 10. I am also using `gulp` 4, that might be it? Do make sure you are using the locally installed `gulp` from this repo, rather than the globally installed gulp, as that is still stuck on 3.

**Comment by AaronNGray** [comment]
@TimvdLippe Are you on Windows or Linux or Mac OSX ?

**Comment by AaronNGray** [comment]
Gulp v3 will try v4

**Comment by AaronNGray** [comment]
package.json has "gulp": "^3.8.8",

**Comment by TimvdLippe** [comment]
> Are you on Windows or Linux or Mac OSX ?

I am on Linux, but others are on OSX. Don't think we have Windows developers on the team atm.

> package.json has "gulp": "^3.8.8",

Hm, you are correct. I thought I had updated that package to 4 :thinking: That might be the issue though.

**Comment by AaronNGray** [comment]
npm install gulp --save-dev gives "gulp": "^3.9.1",

**Comment by AaronNGray** [comment]
gulp 4.0.0 gives :-
> @webcomponents/webcomponentsjs@2.1.3 build C:\Users\aaron\GitHub\webcomponentsjs
> gulp

```
assert.js:337
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\aaron\GitHub\webcomponentsjs\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\aaron\GitHub\webcomponentsjs\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\Users\aaron\GitHub\webcomponentsjs\gulpfile.js:171:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```

**Comment by AaronNGray** [comment]
moving over to try it Debian as I need this working … so often Winblows gets left behind on node.js based 
projects !

**Comment by AaronNGray** [comment]
cool building on Linux ! Dunno if I have the time or the knowledge of the packages to look into it on Windows though. But will run tests on request :)

**Comment by TimvdLippe** [comment]
We currently do not support building the polyfills on Windows right now and I doubt we will in the future. The team develops on Unix systems for building the polyfills. If you are a user of the polyfills, you can use the generated output from NPM, which should work in Windows browser environments.
